ONE-F-M/One-FM

- one_fm/one_fm/page/face_recognition/face_recognition.js
- one_fm/one_fm/page/face_recognition/face_recognition.py
1. Open front camera on mobile.
2. Optimized video size
3. Enrollment process time decreased to almost half from earlier.
> fix: Bugfixes for enrollment process.

- one_fm/utils.py
- Create Job Offer for Shortlisted Applicants
> [WIP] Hiring Process

- one_fm/utils.py
- fix: Create Job Offer for Shortlisted Applicants
> [Fix] Create Job Offer for Shortlisted Applicants

- one_fm/utils.py
- Create Job Offer for Applicants - fix
> [Fix] Create Job Offer for Applicants - fix

- one_fm/config/desktop.py
- one_fm/config/one_fm.py
- fix: Menu for One FM Purchase
> fix: Menu for One FM Purchase

- one_fm/hooks.py
- fix: Purchase receipt - Before Submit
> [Fix] Purchase receipt - Before Submit

- one_fm/hiring/doctype/erf20/erf20.js
- one_fm/hiring/doctype/erf20/erf20.json
- one_fm/hiring/doctype/erf20/erf20.py
- one_fm/hiring/doctype/erf20/guid_html.html
- one_fm/hiring/utils.py
- one_fm/hooks.py
- one_fm/utils.py
- fix: Notify Job Application Created to Recruiter and Requester
- fix: New ERF - performance profile guid
> [Fix] New ERF and Job Application

- one_fm/config/buying.py
- one_fm/one_fm/doctype/pam_visa/pam_visa.js
- one_fm/one_fm/doctype/pam_visa/pam_visa.json
- one_fm/one_fm/doctype/pam_visa/pam_visa.py
- one_fm/purchase/doctype/purchase_settings/purchase_settings.js
- one_fm/purchase/doctype/purchase_settings/purchase_settings.json
- one_fm/purchase/doctype/purchase_settings/purchase_settings.py
- one_fm/purchase/doctype/purchase_settings/test_purchase_settings.py
- one_fm/purchase/doctype/request_for_material/request_for_material.js
- one_fm/purchase/doctype/request_for_material/request_for_material.json
- one_fm/purchase/doctype/request_for_material/request_for_material.py
- fix: Request for Material Accept, Approve or Reject
- feat: Purchase Settings
- fix: PAM Visa field arrangement changed
> [Fix] Request for Material Accept, Approve or Reject

- one_fm/purchase/doctype/request_for_material/request_for_material.js
- one_fm/purchase/doctype/request_for_material/request_for_material.py
- one_fm/purchase/doctype/request_for_material_item/request_for_material_item.json
-fix: Request for Material - Notification and Item Stock details
> [Fix]: Request for Material - Notification and Item Stock details

- one_fm/hooks.py
- one_fm/public/js/doctype_js/sales_invoice.js
@ks093 
1.project should fetch based on customer
2.only display account in income account field in sales invoice item table based on below condition
root_type = Income
is_group = 0
> Added filter for project and income account in sales invoice

- one_fm/operations/doctype/contract_asset/contract_asset.json
- one_fm/operations/doctype/contract_asset/contract_asset.py
- one_fm/operations/doctype/contract_item/contract_item.json
- one_fm/operations/doctype/contract_item/contract_item.py
- one_fm/operations/doctype/contracts/contracts.js
- one_fm/operations/doctype/contracts/contracts.json
- one_fm/operations/doctype/contracts/contracts.py
@ks093 
updated form of contracts doctype in operations module
> Updated Contracts doctype in operations module

- one_fm/accommodation/doctype/accommodation/accommodation.js
- one_fm/accommodation/doctype/accommodation/accommodation.json
- one_fm/accommodation/doctype/bed/bed.json
- one_fm/accommodation/doctype/book_bed/book_bed.json
- one_fm/config/accommodation.py
- one_fm/one_fm/doctype/governorate/governorate.js
- one_fm/one_fm/doctype/governorate/governorate.json
- one_fm/one_fm/doctype/governorate/governorate.py
- one_fm/one_fm/doctype/governorate/test_governorate.py
- one_fm/one_fm/doctype/governorate_area/governorate_area.js
- one_fm/one_fm/doctype/governorate_area/governorate_area.json
- one_fm/one_fm/doctype/governorate_area/governorate_area.py
- one_fm/one_fm/doctype/governorate_area/test_governorate_area.py
- fix: Accommodation - Governorate
> [Fix] Accommodation - Governorate

- one_fm/accommodation/doctype/accommodation/accommodation.json
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.json
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.py
- one_fm/accommodation/doctype/accommodation_unit/accommodation_unit.json
- one_fm/accommodation/doctype/accommodation_unit/accommodation_unit.py
- one_fm/accommodation/doctype/bed/bed.json
- one_fm/accommodation/doctype/bed/bed.py
- fix: Accommodation Module Docs - Allowed Number Validation
> [Fix] Accommodation Module Docs - Allowed Number Validation

- one_fm/accommodation/doctype/bed/bed.json
- one_fm/one_fm/doctype/governorate_area/governorate_area.json
- Fix: Accommodation Module Docs - json changes
> [Fix] Accommodation Module Docs - json changes

- one_fm/accommodation/doctype/accommodation/accommodation.json
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.js
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.json
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.py
- one_fm/accommodation/doctype/accommodation_space_bed/accommodation_space_bed.json
- one_fm/accommodation/doctype/accommodation_space_bed/accommodation_space_bed.py
- one_fm/accommodation/doctype/accommodation_unit/accommodation_unit.json
- one_fm/accommodation/doctype/accommodation_unit/accommodation_unit.py
- one_fm/accommodation/doctype/bed/bed.json
- one_fm/accommodation/doctype/bed/bed.py
- one_fm/accommodation/doctype/floor/floor.js
- one_fm/accommodation/doctype/floor/floor.json
- one_fm/accommodation/doctype/floor/floor.py
- one_fm/accommodation/doctype/floor/test_floor.py
- one_fm/config/accommodation.py
- fix: Accommodation -Bed Creation and Form View changes
> [Fix] Accommodation -Bed Creation and Form View changes

- one_fm/accommodation/doctype/accommodation_space/accommodation_space.py
- one_fm/accommodation/doctype/bed/bed.py
> [Fix] Bed Auto Creation

- one_fm/accommodation/doctype/accommodation/accommodation.json
- one_fm/accommodation/doctype/bed/bed.py
- one_fm/config/accommodation.py
- fix: Accommodation - Update Bed
> [Fix] Accommodation - Update Bed

- one_fm/accommodation/doctype/accommodation/accommodation.json
- fix: Accommodation - Company Name
> [Fix] Accommodation - Company Name

- one_fm/accommodation/doctype/accommodation/accommodation.json
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.json
- one_fm/accommodation/doctype/accommodation_space/accommodation_space.py
- one_fm/accommodation/doctype/accommodation_space_bed/accommodation_space_bed.json
- one_fm/accommodation/doctype/accommodation_unit/accommodation_unit.json
- one_fm/accommodation/doctype/bed/bed.json
- one_fm/accommodation/doctype/bed/bed.py
- fix: Accommodation - Company details fields, Accommodation Doctype search fields updated.
- fix: Accommodation Space and Bed - Update Bed details from Space and Bed.
> [Fix] Accommodation - updated

- one_fm/one_fm/page/roster/roster.js
- one_fm/one_fm/page/roster/roster.py
- one_fm/one_fm/page/roster/staff.html
- one_fm/one_fm/page/roster/staffcard.html
escape post names with single or double quotes 
connect search bar in staff view to backend
> fix: escape post names with single or double quotes,

- one_fm/one_fm/page/roster/roster.css
- one_fm/one_fm/page/roster/roster.js
- one_fm/one_fm/page/roster/roster.py
- one_fm/one_fm/page/roster/staff.html
- one_fm/one_fm/page/roster/staffcard.html
Fix for staff view, 
show loader on assigning staff, 
refactor backend function
> fix: Fix for staff view

- one_fm/one_fm/page/roster/roster.css
- one_fm/one_fm/page/roster/roster.html
- one_fm/one_fm/page/roster/roster.js
- one_fm/one_fm/page/roster/roster.py
- one_fm/one_fm/page/roster/staff.html
- one_fm/one_fm/page/roster/staffcard.html
Adding progress indicators for roster/post edit options
fixes to cardview
refactoring functions to execute immediately instead of background.
> Roster fixes

- one_fm/fixtures/workflow.json
- one_fm/fixtures/workflow_state.json
- one_fm/hooks.py
- one_fm/one_fm/sales_invoice_custom.py
- one_fm/one_fm/timesheet_custom.py
- one_fm/operations/doctype/contract_item/contract_item.json
- one_fm/operations/doctype/contracts/contracts.js
- one_fm/operations/doctype/contracts/contracts.json
- one_fm/operations/doctype/contracts/contracts.py
- one_fm/public/js/doctype_js/sales_invoice.js
@ks093 
1. Adding monthly rate in contracts
2.Applyinh billing rate in timesheet based on monthly rate and also creating sales invoice
3.Workflow for sales invoice
4.removed unwanted code
> Updation for monthly rate in contracts/timesheet/sales_invoice

- one_fm/one_fm/sales_invoice_custom.py
- one_fm/one_fm/timesheet_custom.py
@ks093 
1. added public holiday rate with billing rate for monthly based service item
2. Add value to checkbox field 'edit posting time' in sales invoice (in automatic creation)
> Adding public holiday rate in billing rate/edit posting time value to 1

- one_fm/hooks.py
- one_fm/public/js/doctype_js/asset.js
@ks093 
please check
added new js for asset doctype
> Ab contracts 1

- one_fm/public/js/doctype_js/asset.js
@ks093 
please check 
correction in formatting date
> calculate last day of month

- one_fm/grd/doctype/pifss_form_103/pifss_form_103.json
@ks093 please check
1. changed label of first name,second name,third name, fourth name
> label changes in pifss 103

- one_fm/api/doc_methods/payroll_entry.py
- one_fm/api/mobile/authentication.py
- one_fm/api/mobile/reports.py
- one_fm/api/mobile/roster.py
- one_fm/api/mobile/task_management.py
- one_fm/api/tasks.py
- one_fm/config/legal.py
- one_fm/legal/doctype/legal_settings/legal_settings.js
- one_fm/legal/doctype/legal_settings/legal_settings.json
- one_fm/legal/doctype/legal_settings/legal_settings.py
- one_fm/legal/doctype/legal_settings/test_legal_settings.py
- one_fm/one_fm/page/face_recognition/face_recognition.js
- one_fm/one_fm/page/face_recognition/face_recognition.py
- one_fm/operations/doctype/mom/mom.py
- one_fm/operations/doctype/post_allocation_employee_assignment/post_allocation_employee_assignment.json
- one_fm/operations/doctype/post_allocation_employee_assignment/post_allocation_employee_assignment.py
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.js
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.json
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.py
- one_fm/operations/doctype/post_allocation_plan/test_post_allocation_plan.py
1. Post allocation doctype
2. Legal Settings doctype
3. Bugfixes for Mobile App API
4. Removed unused timestamp variable from face recognition
5. Bugfix for MOM attendees error
> Post allocation plan

- one_fm/config/hr.py
- one_fm/one_fm/doctype/training_evaluation_form/templates/training_evaluation_form.html
- one_fm/one_fm/doctype/training_evaluation_form/templates/training_evaluation_form.js
- one_fm/one_fm/doctype/training_evaluation_form/templates/training_evaluation_form_row.html
- one_fm/one_fm/doctype/training_evaluation_form/test_training_evaluation_form.py
- one_fm/one_fm/doctype/training_evaluation_form/training_evaluation_form.js
- one_fm/one_fm/doctype/training_evaluation_form/training_evaluation_form.json
- one_fm/one_fm/doctype/training_evaluation_form/training_evaluation_form.py
- one_fm/one_fm/doctype/training_evaluation_form/training_evaluation_form_dashboard.py
- one_fm/one_fm/doctype/training_evaluation_form_questions/training_evaluation_form_questions.json
- one_fm/one_fm/doctype/training_evaluation_form_questions/training_evaluation_form_questions.py
- one_fm/one_fm/doctype/training_evaluation_form_response/test_training_evaluation_form_response.py
- one_fm/one_fm/doctype/training_evaluation_form_response/training_evaluation_form_response.js
- one_fm/one_fm/doctype/training_evaluation_form_response/training_evaluation_form_response.json
- one_fm/one_fm/doctype/training_evaluation_form_response/training_evaluation_form_response.py
- one_fm/one_fm/doctype/training_evaluation_form_template/test_training_evaluation_form_template.py
- one_fm/one_fm/doctype/training_evaluation_form_template/training_evaluation_form_template.js
- one_fm/one_fm/doctype/training_evaluation_form_template/training_evaluation_form_template.json
- one_fm/one_fm/doctype/training_evaluation_form_template/training_evaluation_form_template.py
- one_fm/templates/includes/training_evaluation_form/training_evaluation_form.css
- one_fm/templates/includes/training_evaluation_form/training_evaluation_form.js
Doctypes: 
Training Evaluation Form Template
Training Evaluation Form
Training Evaluation Form Response
Training Evaluation Form Questions
> feat: Training Evaluation Form, Anonymous submission

- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.js
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.py
Employee's Gender, Skills, Designation matching with Post
> feat: Post Allocation Plan

- README.md
> Osamaasim patch 1 1

- one_fm/accommodation/report/maintenance_report/maintenance_report.js
- one_fm/accommodation/report/maintenance_report/maintenance_report.json
- one_fm/accommodation/report/maintenance_report/maintenance_report.py
- one_fm/config/gsd.py
- one_fm/hooks.py
- one_fm/purchase/doctype/request_for_material/request_for_material.js
- one_fm/purchase/doctype/request_for_material/request_for_material.json
- one_fm/purchase/doctype/request_for_material/request_for_material.py
- one_fm/purchase/doctype/request_for_material/request_for_material_list.js
- one_fm/purchase/doctype/request_for_material_item/request_for_material_item.json
- requirements.txt
Changes in RFM as well as boiler plate for Maintenance report
> RFM quantity redirection and status functionality implemented.

- one_fm/operations/doctype/operations_post/operations_post.json
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.js
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.json
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.py
10 levels of Priority.
Show today and yesterday's dayoff employees.
Supervisor rotation fix
> fix: Post allocation changes

- one_fm/hooks.py
- one_fm/legal/doctype/penalty/penalty.js
- one_fm/legal/doctype/penalty/penalty.py
- one_fm/purchase/doctype/request_for_material/request_for_material.js
- one_fm/purchase/doctype/request_for_material/request_for_material.json
- one_fm/purchase/doctype/request_for_material/request_for_material.py
- one_fm/purchase/doctype/request_for_purchase/request_for_purchase.py
Altered the auto accept penalty function to reject.
Disabled the RFP button once a RFP is opened against an RFM.
Material transfer button disabled if no stock available.
Created a checkbox to indicate if the request is refundable by the project.
> hotFix:Quick changes in Purchase flow and Penalty doc

- one_fm/one_fm/page/roster/roster.js
- one_fm/one_fm/page/roster/roster.py
Feature Added:
- Added an option to plan a post in roster post view given from and to date.
Fix:
- Added isOt parameter in missing places.
- Corrected count of basic roster scheduled and available employee list.
- Fixed cancel post bug.
> Roster feature added and fixes

- one_fm/one_fm/page/roster/roster.py
- Enqueued database operations in edit post.
- Removed unnecessary value assignment in plan post operation.
> Hotfix: Enqueued edit post operations

- one_fm/api/mobile/legal.py
- one_fm/one_fm/doctype/leave_application/leave_application_list.js
- one_fm/purchase/doctype/request_for_material/request_for_material.js
- one_fm/purchase/doctype/request_for_material/request_for_material.py
- Changes in Mobile Penalty to resolve imports. (Kartik)
- List view for leave application updated.
- Filters and validations added in RFM.
> hotFix:Minor changes in penalty API imports,leave app list and RFM

- one_fm/one_fm/page/roster/roster.js
- one_fm/one_fm/page/roster/roster.py
- Added end date field for cancel post operation.
- Fixed enqueued method args.
> Fix: Added end date for cancel post operation

- one_fm/operations/doctype/employee_certification/employee_certification.json
- one_fm/operations/doctype/employee_certification/employee_certification.py
- one_fm/operations/doctype/employee_license/employee_license.json
- one_fm/operations/doctype/employee_license/employee_license.py
- Exported customizations form HR module to operations module.
> Fix: Exported doctypes to opeations module

- one_fm/api/doc_events.py
- one_fm/hooks.py
- one_fm/operations/doctype/certification/certification.js
- one_fm/operations/doctype/certification/certification.json
- one_fm/operations/doctype/certification/certification.py
- one_fm/operations/doctype/certification/test_certification.py
- one_fm/operations/doctype/license/license.js
- one_fm/operations/doctype/license/license.json
- one_fm/operations/doctype/license/license.py
- one_fm/operations/doctype/license/test_license.py
- Exported customized doctypes.
- Expiry date validation for certifications and licenses in Employee Skill Map doctype.
> Validate expiry date in L&C

- one_fm/api/doc_events.py
- one_fm/hooks.py
- one_fm/operations/doctype/certification/certification.json
- one_fm/operations/doctype/license/license.json
- one_fm/operations/doctype/operations_shift/operations_shift.json
- one_fm/operations/doctype/operations_shift/operations_shift.py
- one_fm/operations/doctype/post_allocation_plan/post_allocation_plan.js
- one_fm/operations/doctype/service_type/service_type.js
- one_fm/operations/doctype/service_type/service_type.json
- one_fm/operations/doctype/service_type/service_type.py
- one_fm/operations/doctype/service_type/test_service_type.py
- Added Operations Manager role to Certification and License doctypes.
> Fix: Added role permissions, updated post allocation plan and included "service type" in operations shift.

- one_fm/patches.txt
- one_fm/patches/v1_0/change_in_naming_series_operations_post.py
- one_fm/patches/v1_0/schedule_posts.py
- Added patch to schedule all posts(set post status as planned) under site: Airport Terminal 4.
- Added patch to rename all Operations Post documents with new naming series - including the service type [Did not include it in patches.txt as this patch needs to be executed at later stage].
> Added patches 

- one_fm/one_fm/doctype/training_program_certificate/training_program_certificate.json
- Removed fetch from in Training Program Certificate doctype trainer name and trainer email fields.
- Changed company field type from Read only to Data and check Read only option for future customizations.
> Changed field fetch from location
